FROM ruby:2.6.9-alpine

ENV APP_PATH /var/app
ENV BUNDLE_VERSION 2.3.7
ENV BUNDLE_PATH /usr/local/bundle/gems 
ENV TMP_PATH /tmp/ 
ENV RAILS_LOG_TO_STDOUT true 
ENV RAILS_PORT 3000

COPY ./dev-docker-entrypoint.sh /usr/local/dev-entrypoint.sh 
# COPY ./dev-docker-entrypoint.sh /usr/bin/dev-entrypoint.sh 
# COPY ./test-docker-entrypoint.sh /usr/local/test-entrypoint.sh 

# RUN chmod -x /usr/local/dev-entrypoint.sh 
# RUN chmod -x /usr/bin/dev-entrypoint.sh 
RUN chmod +x /usr/local/dev-entrypoint.sh 
# RUN chmod +x /usr/bin/dev-entrypoint.sh

# && chmod -x /usr/local/test-entrypoint.sh 

#setup deps for rails
RUN apk -U add --no-cache \
build-base \
git \
mysql-dev \
mysql-client \
libxslt-dev \ 
nodejs \
yarn \
imagemagick \
tzdata \
less \
sqlite-dev \
&& rm -rf /var/cache/apk/* \
&& mkdir -p $APP_PATH 

# RUN gem install bundler --version "BUNDLE_VERSION" \ 
# && rm -rf $GEM_HOME/cache/* 

RUN gem install bundler -v "$BUNDLE_VERSION" && rm -rf /usr/local/bundle/cache/*


WORKDIR $APP_PATH 
# Copy Gemfile and Gemfile.lock to the container
COPY Gemfile Gemfile.lock ./


EXPOSE $RAILS_PORT 

ENTRYPOINT ["bundle", "exec"]