# FROM ruby:2.6.9-alpine
# FROM ruby:2.7.6-alpine
FROM ruby:3.1.4

ENV WEB_APP_PATH /var/app
ENV BUNDLE_VERSION 2.3.7
ENV BUNDLE_PATH /usr/local/bundle/gems 
ENV TMP_PATH /tmp/ 
ENV RAILS_LOG_TO_STDOUT true 
ENV RAILS_PORT 3000

COPY ./dev-docker-entrypoint.sh /usr/local/dev-entrypoint.sh 
RUN chmod +x /usr/local/dev-entrypoint.sh 

COPY ./test-docker-entrypoint.sh /usr/local/test-entrypoint.sh 
RUN chmod +x /usr/local/test-entrypoint.sh 



RUN apt-get update -qq && apt-get install -y --no-install-recommends \
build-essential curl git default-libmysqlclient-dev libssl-dev sqlite3 libsqlite3-dev libvips vim \
chromium

## Install yarn and nodejs
RUN curl -sL https://deb.nodesource.com/setup_14.x  | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
# RUN echo "deb https://deb.nodesource.com/node_14.x focal main"
RUN apt-get update -qq && apt-get install -y nodejs yarn

RUN gem install bundler -v "$BUNDLE_VERSION" && rm -rf /usr/local/bundle/cache/* && rm -rf $GEM_HOME/cache/*

WORKDIR $WEB_APP_PATH 

# gem install bundler -v "2.3.7" && rm -rf /usr/local/bundle/cache/*

# Copy Gemfile and Gemfile.lock to the container
# COPY Gemfile Gemfile.lock ./
COPY Gemfile ./

EXPOSE $RAILS_PORT 
